PERSONAS = {
    "robert": {
        "name": "Robert Chen",
        "age": 58,
        "occupation": "Retired Mechanical Engineer",
        "portfolio_value": "$400k",
        "current_provider": "Fidelity",
        "difficulty": "Hard",
        "voice_id": "VR6AewLTigWG4xSOukaG",
        "main_objection": "I already manage it myself, done fine for 30 years",
        "secondary_objections": [
            "How did you get my number?",
            "What makes you different?",
            "I don't pay fees for something I do myself",
        ],
        "background": "Retired mechanical engineer, highly analytical, self-directed investor for 30 years, has existing Fidelity relationship, skeptical of anyone who can't beat his own returns",
        "scoring_weights": {
            "objection_handling": 1.5,
            "tone_confidence": 1.3,
            "close_attempt": 1.2,
        },
    },
    "sarah": {
        "name": "Sarah Mitchell",
        "age": 45,
        "occupation": "VP of Operations",
        "portfolio_value": "$750k",
        "current_provider": "Vanguard",
        "difficulty": "Medium",
        "voice_id": "XB0fDUnXU5powFXDhCwa",
        "main_objection": "Can you just send me an email?",
        "secondary_objections": [
            "I don't have time",
            "Everything's on autopilot",
            "What's this going to cost me?",
        ],
        "background": "Senior executive, time-poor, values efficiency, already has a competent Vanguard setup, needs a compelling reason to switch or engage",
        "scoring_weights": {
            "objection_handling": 1.1,
            "tone_confidence": 1.0,
            "close_attempt": 1.1,
        },
    },
    "marcus": {
        "name": "Marcus Johnson",
        "age": 34,
        "occupation": "Startup Founder",
        "portfolio_value": "$250k",
        "current_provider": "Robinhood + Crypto",
        "difficulty": "Easy",
        "voice_id": "IKne3meq5aSn9XLyUdCD",
        "main_objection": "I've been managing my own stuff, it's been fine",
        "secondary_objections": [
            "Been meaning to get around to that",
            "What's your minimum?",
            "Can I check your website first?",
        ],
        "background": "Young founder, crypto-oriented, open to new things but easily distracted, needs education more than persuasion",
        "scoring_weights": {
            "objection_handling": 0.8,
            "tone_confidence": 1.2,
            "close_attempt": 0.9,
        },
    },
}
